language: ruby
rvm:
- 2.1
install:
  - bundler install

script: jekyll build && htmlproof ./_site

# branch whitelist
branches:
  only:
  - master     # test the master branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

  # From: http://jekyllrb.com/docs/continuous-integration/