### GENERAL SETTINGS ###

# Site settings
title: CoderDojo Kalmar
description: "CoderDojo är ett globalt nätverk av öppna, mentorsledda, oberoende, gemenskaphetsdrivna programmeringsstugor för unga. Ungdomarna, i åldrarna 7-17, lär sig koda, utveckla webbsidor, appar, program, spel och utforska teknik i en kreativ miljö. Förutom att lära sig koda så träffar deltagarna andra med samma intresse och får visa upp vad de arbetar med."
analytics: UA-59960580-1
baseurl: "" #important: start with /
url: "http://kalmar.coderdojo.se"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#5CA18B" #"#F70031" 
  primary_rgb: "92,161,139" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#5CA18B"
  link_hover: "#E3998B"
  footer_heading: "#ffffff"
  footer_content: "#C0A78E"


   #primary: "#00b3fe" #"#F70031" 
  #primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  #secondary: "#384452" #"#33004D"
  #link: "#428bca"
  #link_hover: "#01b2fe"
  #footer_heading: "#ffffff"
  #footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: facebook
    url: https://www.facebook.com/groups/coderdojo.kalmar.public/

    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - Nygatan 34
    - Kalmar
email: kalmar.coderdojo@gmail.com
tel: 076-138 10 08 (Linnéa Josefsson)


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
members:
  - name: Johan Leitet
    position: Huvudmentor
    text: Johan undervisar i webbprogrammering på Linnéuniversitetet och är intresserad av allt som rör webben och internet.
    img: team01.jpg
    social:
      - title: envelope #use for email address
        url: mailto:johan.leitet@lnu.se
      - title: home
        url: https://johan.leitet.se
      - title: twitter
        url: http://twitter.com/leitet
      - title: facebook
        url: http://www.facebook.com/leitet
      - title: instagram
        url: https://instagram.com/leitet
      - title: github
        url: https://github.com/leitet

  - name: Daniel Toll
    position: Huvudmentor
    text: Daniel undervisar programmering på Linneuniversitetet, han forskar även om programkodskvalitet.
    img: team02.jpg
    social:
      - title: envelope #use for email address
        url: mailto:daniel.toll@lnu.se
      - title: home
        url: https://coursepress.lnu.se/daniel-toll/
  - name: Linnéa Josefsson
    position: Huvudmentor
    text: Linnéa är kommunikatör på AV-Media och har alltid spännande robotar och annat kul att visa upp!
    img: team03.jpg
    social:
      - title: envelope #use for email address
        url: mailto:linnea@avmkl.se
      - title: home
        url: http://www.avmkl.se/kontakt/75-linnea-j
  - name: Jacob Lindehoff
    position: Huvudmentor
    text: Jacob undervisar främst inom systemadministration på Linnéuniversitetet. På fritiden så gillar han att automatisera allt i sitt hem.
    img: team04.jpg
    social:
      - title: envelope #use for email address
        url: mailto:jacob.lindehoff@lnu.se
      - title: twitter
        url: http://twitter.com/lindehoff

  - name: Rasmus Israelsson
    position: Mentor
    img: rasmus.jpg

  - name: Helen Madestam
    position: Mentor
    img: helen.jpg
    social:
    - title: envelope
      url: mailto:helen.madestam@tieto.com

  - name: Joel Stahre
    position: Mentor
    img: joel.jpg
    social:
      - title: envelope
        url: mailto:joelstahre@gmail.com
    
    
# Clients information. Shown on Home and About pages.
clients:
  - name: AvMedia Kalmar
    img: client01.png
  - name: Linnéuniversitetet
    img: client02.png
  - name: Kalmar Science Park
    img: client03.png
  - name: CoderDojo
    img: client04.png
    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "CoderDojo är ett globalt nätverk av öppna, mentorsledda, oberoende, gemenskaphetsdrivna programmeringsstugor för unga. Ungdomarna, i åldrarna 7-17, lär sig koda, utveckla webbsidor, appar, program, spel och utforska teknik i en kreativ miljö. Förutom att lära sig koda så träffar deltagarna andra med samma intresse och får visa upp vad de arbetar med."

# Testimonial content. Shown on Home and About page. 
testimonial:
    message: "Education should prepare young people for jobs that do not yet exist, using technologies that have not yet been invented, to solve problems of which we are not yet aware."
    author: Richard Riley
    position: Former United States Secretary of Education

# Travis bundles all gems in the vendor directory on its build servers, which Jekyll will mistakenly read and explode on. To avoid this, exclude vendor in your _config.yml:
#http://jekyllrb.com/docs/continuous-integration/
exclude: [vendor]

